services:
  tafrigh-bot:
    build: .
    container_name: tafrigh-fatwa-bot
    restart: unless-stopped
    ports:
      - "5060:5060"
    environment:
      - TELEGRAM_BOT_TOKEN=7855088071:AAHkvP8po77ITSruud1fO_Gp3SJOituI2xI
      - GROQ_API_KEY=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
      - WEBHOOK_URL=
      - PORT=5060
      - DB_PATH=/app/data/fatwas_bot.db
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
